pipeline {
    agent any
    environment {
        REGISTRY = "eu.gcr.io/lbg-mea-17"
        VERSION = "v2"
    }
  stages {
    stage('Build') {
            steps {
                sh '''
                    docker build -t $REGISTRY/task1_image:$VERSION Task1
                    
                '''   
            }
        }
      stage('Test') {
            steps {
                echo "testing...."
                sh "sleep 1"
                echo "Passed!"
            }
        }
        stage('Push') {
            steps {
                sh '''
                echo "Push to registry....defined in environment variable"
                gcloud config set account jayne-srv-storage-admin@lbg-mea-17.iam.gserviceaccount.com
                docker push $REGISTRY/task1_image:$VERSION
                ''' 
            }
        }
      stage('Deploy') {
            steps {
                sh '''
                    gcloud config set account jayne-jenkins-k8s-srv@lbg-mea-17.iam.gserviceaccount.com
                    kubectl apply -f Task1
                '''
            }
        }
  }
  post {
    always {
        sh '''
        docker system prune -f
        gcloud config set account null
        '''
    }
  }
}